/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Discount.DiscountController;
import GUI.TableWrappers.DiscountTableModel;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author amirharvey
 */
public class FlatDiscount extends javax.swing.JFrame {

    private DiscountManagement Parent;

    /**
     * Creates new form FlatDiscount
     */
    public FlatDiscount(DiscountManagement _parent) {
        Parent = _parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DescriptionText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountErrLabel = new javax.swing.JLabel();
        AmountText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        NameText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("NAME:");

        ConfirmButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ConfirmButton.setText("CONFIRM");
        ConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmButtonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("DESCRIPTION:");

        DescriptionText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("AMOUNT:");

        amountErrLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        amountErrLabel.setText("");
        amountErrLabel.setForeground(Color.RED);

        AmountText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmButton)
                .addGap(31, 31, 31))

            .addGroup(jPanel1Layout.createParallelGroup()
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30,30,30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                    )
                        .addGap(110,110,110)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AmountText, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addComponent(DescriptionText)
                        .addComponent(NameText)
                    )
                    .addGap(30,30,30)
                )
                 .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(30,30,30)
                         .addComponent(amountErrLabel)
                 )
        ));
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18,18,18)
                .addComponent(amountErrLabel)
                    .addGap(45, 45, 45)
                .addComponent(ConfirmButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButtonMouseClicked
        String DiscountName = NameText.getText();
        String DiscountDescription = DescriptionText.getText();
        Float DiscountAmount = Float.parseFloat(AmountText.getText());
        if (DiscountAmount > .3f && amountErrLabel.getText().length() < 30) {
            amountErrLabel.setText("Amount is multiplied by 100 to get percentage,\ni.e .05 = 5% discount, are you sure?");
            return;
        }
        System.out.println(DiscountName + ": " + DiscountDescription + ": " + DiscountAmount.toString());

        if (DiscountName.isBlank()) {
            amountErrLabel.setText("Name cannot be blank");
            return;
        }

        if (DiscountDescription.isBlank()) {
            amountErrLabel.setText("Description cannot be blank");
            return;
        }

        JTable DiscountTable = Parent.getDiscountTable();
        ((DiscountTableModel)DiscountTable.getModel()).addDiscount(DiscountController.createFixedDiscountPlan(DiscountName, DiscountDescription, DiscountAmount));

        this.dispose();
    }//GEN-LAST:event_ConfirmButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountText;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JTextField DescriptionText;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel amountErrLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
