/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Discount.DiscountController;
import Discount.JobFlexibleData;
import GUI.TableWrappers.DiscountTableModel;
import GUI.TableWrappers.JobDiscountTableModel;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author amirharvey
 */
public class FlexibleDiscountPopUp extends javax.swing.JFrame {

    private DiscountManagement Parent;
    public ArrayList<JobFlexibleData> jobdatas;

    /** Creates new form FlexibleDiscount */
    public FlexibleDiscountPopUp(DiscountManagement _parent) {
        Parent = _parent; initComponents(); jobdatas = new ArrayList<>();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ConfirmButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        DescriptionText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JobDiscountTable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        StartPriceText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EndPriceText = new javax.swing.JTextField();
        PercentageText2 = new javax.swing.JTextField();
        ErrorLabel = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setForeground(new java.awt.Color(255, 255, 204));

        NameText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("NAME:");

        AddButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        AddButton.setText("ADD");

        ConfirmButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ConfirmButton2.setText("CONFIRM");
        ConfirmButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmButton2MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("DESCRIPTION:");

        ErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ErrorLabel.setText("");
        ErrorLabel.setForeground(Color.RED);

        DescriptionText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("AMOUNTS:");

        JobDiscountTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        JobDiscountTable.setModel(new JobDiscountTableModel());
        jScrollPane3.setViewportView(JobDiscountTable);

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Processing.Controller.getJobTypes()));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Start Price:");

        StartPriceText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("End Price:");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Amount:");

        EndPriceText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        PercentageText2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(NameText)
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ErrorLabel)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ConfirmButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StartPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EndPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PercentageText2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18,18,18)
                                    .addComponent(AddButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addComponent(ErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(StartPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(EndPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(PercentageText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(ConfirmButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (StartPriceText.getText().isBlank()) {
                    ErrorLabel.setText("StartPrice must be entered, even if 0");
                    return;
                }

                if (EndPriceText.getText().isBlank()) {
                    ErrorLabel.setText("EndPrice must be entered, even if 0");
                    return;
                }

                if (PercentageText2.getText().isBlank()) {
                    ErrorLabel.setText("Amount must be entered");
                    return;
                }

                Float StartPrice = Float.parseFloat(StartPriceText.getText());
                Float EndPrice = Float.parseFloat(EndPriceText.getText());
                Float Amount = Float.parseFloat(PercentageText2.getText());

                if (EndPrice <= StartPrice) {
                    ErrorLabel.setText("EndPrice must be greater than StartPrice");
                    return;
                }

                if (Amount == 0) {
                    ErrorLabel.setText("Zero amount forbidden");
                    return;
                }

                if (Amount > .5f && !ErrorLabel.getText().contains("Amount is ")) {
                    ErrorLabel.setText("Amount is " + ((Float)(Amount*100f)).toString()+"% are you sure this is correct?");
                    return;
                }

                ErrorLabel.setText("");

                JobFlexibleData d = new JobFlexibleData( jComboBox1.getSelectedIndex()+1, StartPrice, EndPrice, Amount );
                System.out.println(d.JobType.toString());
                ((JobDiscountTableModel)JobDiscountTable.getModel()).addElement(d);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButton2MouseClicked
        if (NameText.getText().isBlank()) {
            ErrorLabel.setText("Name cannot be blank");
            return;
        }

        if (DescriptionText.getText().isBlank()) {
            ErrorLabel.setText("Description cannot be blank");
            return;
        }

        ArrayList<JobFlexibleData> d = ((JobDiscountTableModel)JobDiscountTable.getModel()).getValues();
        Discount.Discount D = DiscountController.createFlexibleDiscountPlan(NameText.getText(), DescriptionText.getText(), d);
        ((DiscountTableModel)Parent.getDiscountTable().getModel()).addDiscount(D);

        this.dispose();
    }//GEN-LAST:event_ConfirmButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JobDiscountTable;
    private javax.swing.JButton ConfirmButton2;
    private javax.swing.JTextField DescriptionText;
    private javax.swing.JTextField EndPriceText;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField PercentageText2;
    private javax.swing.JTextField StartPriceText;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton AddButton;
    // End of variables declaration//GEN-END:variables

}
