/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Account.CustomerAccount;
import DB.DBConnWrapper;
import Users.User;
import Users.UserController;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author amirharvey
 */
public class StaffManagement extends javax.swing.JFrame {

    /**
     * Creates new form StaffManagement
     */
    public StaffManagement() {
        initComponents();
    }

    private void SetSelectedStaff(User c) {
        SelectedStaff = c;
        NameText.setText(c.getName());
        UsernameText.setText(c.getUsername());
        PasswordText.setText(c.getPassword());
        AddressText.setText(c.getAddress());
        DepartmentText.setText(c.getDepartment());
        RoleDropDown.setSelectedIndex(c.getRole()-1);
        SelectedStaffLabel.setText("SELECTED: " + c.getName());
    }

    private void SetError(String error) {
        ErrorLabel.setText(error);
    }

    private void ClearError() {
        ErrorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        MyTasksButton = new javax.swing.JButton();
        NewCustomerButton = new javax.swing.JButton();
        AddJobButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        ProcessPaymentButton = new javax.swing.JButton();
        AdminButton = new javax.swing.JButton();
        ManageCustomerButton = new javax.swing.JButton();
        ManageDiscountsButton = new javax.swing.JButton();
        ManageStaffButton = new javax.swing.JButton();
        ManageReportButton = new javax.swing.JButton();
        ManageDatabaseButton = new javax.swing.JButton();
        ManageTasksButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RoleDropDown = new javax.swing.JComboBox<>();
        DeleteButton = new javax.swing.JButton();
        AddAsNewButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        NameText = new javax.swing.JTextField();
        UsernameText = new javax.swing.JTextField();
        AddressText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JTextField();
        DepartmentText = new javax.swing.JTextField();
        SelectedStaffLabel = new javax.swing.JLabel();
        SelectStaff = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();

        SelectStaff.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SelectedStaffLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Bloomsbury's Image Processing Laboratory");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);

        MyTasksButton.setText("My Tasks");
        MyTasksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyTasksButtonMouseClicked(evt);
            }
        });
        MyTasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTasksButtonActionPerformed(evt);
            }
        });

        NewCustomerButton.setText("New Customer");
        NewCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewCustomerButtonMouseClicked(evt);
            }
        });

        AddJobButton.setText("Add Job");
        AddJobButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddJobButtonMouseClicked(evt);
            }
        });

        HomeButton.setText("Home");
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
        });

        ProcessPaymentButton.setText("Process Payment");
        ProcessPaymentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProcessPaymentButtonMouseClicked(evt);
            }
        });
        ProcessPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessPaymentButtonActionPerformed(evt);
            }
        });

        AdminButton.setText("Administration");
        AdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminButtonMouseClicked(evt);
            }
        });
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        ManageCustomerButton.setText("Manage Customer");
        ManageCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCustomerButtonMouseClicked(evt);
            }
        });
        ManageCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCustomerButtonActionPerformed(evt);
            }
        });

        ManageDiscountsButton.setText("Manage Discounts");
        ManageDiscountsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageDiscountsButtonMouseClicked(evt);
            }
        });
        ManageDiscountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDiscountsButtonActionPerformed(evt);
            }
        });

        ManageStaffButton.setText("Manage Staff");
        ManageStaffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageStaffButtonMouseClicked(evt);
            }
        });
        ManageStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageStaffButtonActionPerformed(evt);
            }
        });

        ManageReportButton.setText("Manage Report");
        ManageReportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageReportButtonMouseClicked(evt);
            }
        });
        ManageReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageReportButtonActionPerformed(evt);
            }
        });

        ManageDatabaseButton.setText("Manage Database");
        ManageDatabaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageDatabaseButtonMouseClicked(evt);
            }
        });
        ManageDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDatabaseButtonActionPerformed(evt);
            }
        });

        ManageTasksButton.setText("Manage Tasks");
        ManageTasksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageTasksButtonMouseClicked(evt);
            }
        });
        ManageTasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageTasksButtonActionPerformed(evt);
            }
        });

        NameText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ClearError();
            }
        });
        UsernameText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ClearError();
            }
        });
        PasswordText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ClearError();
            }
        });
        AddressText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ClearError();
            }
        });
        DepartmentText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ClearError();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ClearError();
            }
        });

        SelectStaff.setText("SELECT STAFF");
        SelectedStaffLabel.setText("STAFF: NONE SELECTED");

        SelectStaff.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AddJobPopUp.SelectMode = "STAFF";
                SelectionPopUpCaller SPUC = new SelectionPopUpCaller();
                SPUC.addSelectionListener(new SelectionListener() {
                    @Override
                    void selectionMade(Object Selection) {
                        User c = (User) Selection;
                        SetSelectedStaff(c);
                    }
                });
                new AddJobPopUp(SPUC).setVisible(true);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyTasksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NewCustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProcessPaymentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddJobButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageCustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageDiscountsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageStaffButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageDatabaseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageTasksButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MyTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AddJobButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(NewCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ProcessPaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ManageCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ManageDiscountsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ManageStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ManageReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ManageDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ManageTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("ADDRESS:");

        ErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ErrorLabel.setText("");
        ErrorLabel.setForeground(Color.RED);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("NAME:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("PASSWORD:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("USERNAME:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("DEPARTMENT:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("ROLE:");

        RoleDropDown.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        RoleDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OfficeManager", "ShiftManager", "Receptionist", "Technician" }));

        DeleteButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        DeleteButton.setText("DELETE");

        AddAsNewButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        AddAsNewButton.setText("ADD AS NEW");

        SaveButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SaveButton.setText("SAVE");

        NameText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        UsernameText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });

        AddressText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        AddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextActionPerformed(evt);
            }
        });

        PasswordText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });

        DepartmentText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        DepartmentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                .addComponent(SelectedStaffLabel)
                                .addComponent(ErrorLabel))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameText)
                                    .addComponent(UsernameText)
                                    .addComponent(PasswordText)
                                .addComponent(SelectStaff)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(AddAsNewButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SaveButton)
                                        .addGap(20, 20, 20))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(RoleDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DepartmentText)
                                    .addComponent(AddressText)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(DeleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(ErrorLabel)
                            .addGap(18,18,18)
                            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(SelectedStaffLabel)
                                .addComponent(SelectStaff)
                            )
                            .addGap(18,18,18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(DepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(RoleDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteButton)
                            .addComponent(AddAsNewButton)
                            .addComponent(SaveButton)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
        );

        DeleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DeleteSelected();
            }
        });

        AddAsNewButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AddNew();
            }
        });

        SaveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (SelectedStaff == null) {
                    return;
                }

                String name = NameText.getText();
                String username = UsernameText.getText();
                String password = PasswordText.getText();
                String address = AddressText.getText();
                String department = DepartmentText.getText();
                Integer role = RoleDropDown.getSelectedIndex()+1;

                if (name.isBlank()) {
                    SetError("Name cannot be blank.");
                    return;
                }
                if (username.isBlank()) {
                    SetError("Username cannot be blank.");
                    return;
                }
                if (password.isBlank()) {
                    SetError("Password cannot be blank.");
                    return;
                }
                if (address.isBlank()) {
                    SetError("Address cannot be blank.");
                    return;
                }
                if (department.isBlank()) {
                    SetError("Department cannot be blank.");
                    return;
                }
                if (role < SelectedStaff.getRole() && !ErrorLabel.getText().contains("Role will be increased")) {
                    SetError("Role will be increased, are you sure?");
                    return;
                }

                Save();
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyTasksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTasksButtonMouseClicked
        this.dispose();
        MyTasks obj = new
        MyTasks();
        obj.setVisible(true);
    }//GEN-LAST:event_MyTasksButtonMouseClicked

    private void MyTasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTasksButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyTasksButtonActionPerformed

    private void NewCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCustomerButtonMouseClicked
        this.dispose();
        NewCustomer obj = new
        NewCustomer();
        obj.setVisible(true);
    }//GEN-LAST:event_NewCustomerButtonMouseClicked

    private void AddJobButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddJobButtonMouseClicked
        this.dispose();
        AddJob obj = new
        AddJob();
        obj.setVisible(true);
    }//GEN-LAST:event_AddJobButtonMouseClicked

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        this.dispose();
        Home obj = new
        Home();
        obj.setVisible(true);
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void ProcessPaymentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProcessPaymentButtonMouseClicked
        this.dispose();
        Payment obj = new
        Payment();
        obj.setVisible(true);
    }//GEN-LAST:event_ProcessPaymentButtonMouseClicked

    private void ProcessPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessPaymentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProcessPaymentButtonActionPerformed

    private void AdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminButtonMouseClicked
        this.dispose();
        AdminLogin obj = new
        AdminLogin();
        obj.setVisible(true);
    }//GEN-LAST:event_AdminButtonMouseClicked

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void ManageCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCustomerButtonMouseClicked
        this.dispose();
        ManageCustomer obj = new
        ManageCustomer();
        obj.setVisible(true);
    }//GEN-LAST:event_ManageCustomerButtonMouseClicked

    private void ManageCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageCustomerButtonActionPerformed

    private void ManageDiscountsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageDiscountsButtonMouseClicked
        this.dispose();
        DiscountManagement obj = new
        DiscountManagement();
        obj.setVisible(true);
    }//GEN-LAST:event_ManageDiscountsButtonMouseClicked

    private void ManageDiscountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDiscountsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageDiscountsButtonActionPerformed

    private void ManageStaffButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageStaffButtonMouseClicked
        this.dispose();
        StaffManagement obj = new
        StaffManagement();
        obj.setVisible(true);
    }//GEN-LAST:event_ManageStaffButtonMouseClicked

    private void ManageStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageStaffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageStaffButtonActionPerformed

    private void ManageReportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageReportButtonMouseClicked
        this.dispose();
        ReportManagement obj = new
        ReportManagement();
        obj.setVisible(true);
    }//GEN-LAST:event_ManageReportButtonMouseClicked

    private void ManageReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageReportButtonActionPerformed

    private void ManageDatabaseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageDatabaseButtonMouseClicked
       this.dispose();
        DatabaseManagement obj = new
        DatabaseManagement();
        obj.setVisible(true);
    }//GEN-LAST:event_ManageDatabaseButtonMouseClicked

    private void ManageDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDatabaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageDatabaseButtonActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void AddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void DepartmentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentTextActionPerformed

    private void ManageTasksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageTasksButtonMouseClicked
        this.dispose();
        TaskManagement obj = new
        TaskManagement();
        obj.setVisible(true);
    }//GEN-LAST:event_ManageTasksButtonMouseClicked

    private void ManageTasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageTasksButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageTasksButtonActionPerformed

    private void DeleteSelected() {
        if (SelectedStaff == null) {
            return;
        }
        if (SelectedStaff == UserController.currentUser) {
            return;
        }
        String query = "DELETE FROM StaffAccount WHERE id = " + SelectedStaff.getId().toString();
        Connection conn = DBConnWrapper.getConnection();
        try {
            conn.createStatement().executeUpdate(query);
        }
        catch (SQLException _e) {
            _e.printStackTrace();
        }
    }

    private void AddNew() {
        String Username = UsernameText.getText();
        String query = "SELECT COUNT(*) FROM StaffAccount WHERE Username = '" + Username + "'";
        Connection conn = DBConnWrapper.getConnection();
        try {
            ResultSet RS = conn.createStatement().executeQuery(query);
            while (RS.next()) {
                if (RS.getInt("COUNT(*)") > 0) {
                    UsernameText.setText("NAME TAKEN");
                    return;
                }
            }
        }
        catch (SQLException _e) {
            _e.printStackTrace();
        }
        if (PasswordText.getText().isBlank() || PasswordText.getText().length() < 5) {
            PasswordText.setText("PASSWORD TOO SIMPLE");
            return;
        }
        if (NameText.getText().isBlank()) {
            NameText.setText("NAME MUST BE ENTERED!");
            return;
        }
        if (AddressText.getText().isBlank()) {
            AddressText.setText("ADDRESS MUST BE ENTERED!");
            return;
        }
        if (DepartmentText.getText().isBlank()) {
            DepartmentText.setText("DEPARTMENT MUST BE ENTERED!");
        }
        query = "INSERT INTO StaffAccount(`Role`, `Username`, `Password`, `Name`, `Address`, `Department`) VALUES\n"
                + "(" + ((Integer)(RoleDropDown.getSelectedIndex()+1)).toString() + ",\n"
                + "'" + Username + "',\n"
                + "'" + PasswordText.getText() + "',\n"
                + "'" + NameText.getText() + "',\n"
                + "'" + AddressText.getText() + "',\n"
                + "'" + DepartmentText.getText() + "'\n"
                + ");";
        System.out.println(query);
        try {
            conn.createStatement().executeUpdate(query);
        }
        catch (SQLException _e) {
            _e.printStackTrace();
        }
    }

    private void Save() {
        String name = NameText.getText();
        String username = UsernameText.getText();
        String password = PasswordText.getText();
        String address = AddressText.getText();
        String department = DepartmentText.getText();
        Integer role = RoleDropDown.getSelectedIndex()+1;

        String query = "UPDATE StaffAccount\n"
                + "SET " + "Role = " + role.toString() + ", "
                + "Username = '" + username + "', "
                + "Password = '" + password + "', "
                + "Name = '" + name + "', "
                + "Address = '" + address + "', "
                + "Department = '" + department + "'\n"
                + "WHERE id = " + SelectedStaff.getId().toString();
        Connection conn = DBConnWrapper.getConnection();
        try {
            conn.createStatement().executeUpdate(query);
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAsNewButton;
    private javax.swing.JButton AddJobButton;
    private javax.swing.JTextField AddressText;
    private javax.swing.JButton AdminButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField DepartmentText;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton ManageCustomerButton;
    private javax.swing.JButton ManageDatabaseButton;
    private javax.swing.JButton ManageDiscountsButton;
    private javax.swing.JButton ManageReportButton;
    private javax.swing.JButton ManageStaffButton;
    private javax.swing.JButton ManageTasksButton;
    private javax.swing.JButton MyTasksButton;
    private javax.swing.JTextField NameText;
    private javax.swing.JButton NewCustomerButton;
    private javax.swing.JTextField PasswordText;
    private javax.swing.JButton ProcessPaymentButton;
    private javax.swing.JComboBox<String> RoleDropDown;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel SelectedStaffLabel;
    private javax.swing.JButton SelectStaff;
    private User SelectedStaff;
    private javax.swing.JLabel ErrorLabel;
    // End of variables declaration//GEN-END:variables
}
