/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Discount.TaskPercentPair;
import Discount.Discount;
import GUI.TableWrappers.DiscountTableModel;
import GUI.TableWrappers.TaskDiscountTableModel;
import Discount.VariableDiscount;
import Discount.DiscountController;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author amirharvey
 */
public class VariableDiscountPopUp extends javax.swing.JFrame {
    private ArrayList<TaskPercentPair> discountArray;

    DiscountManagement Parent;
    /**
     * Creates new form VariableDiscount
     */
    public VariableDiscountPopUp(DiscountManagement _parent) {
        initComponents();
        Parent = _parent;
        discountArray = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ConfirmButton2 = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DescriptionText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TaskDiscountsTable = new javax.swing.JTable();
        TaskTypeDropDown = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        PercentageText = new javax.swing.JTextField();
        ErrLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setForeground(new java.awt.Color(255, 255, 204));

        NameText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("NAME:");

        ErrLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ErrLabel.setText("");
        ErrLabel.setForeground(Color.RED);

        ConfirmButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ConfirmButton2.setText("CONFIRM");
        ConfirmButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmButton2MouseClicked(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        AddButton.setText("ADD JOB%");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("DESCRIPTION:");

        DescriptionText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("JOB DISCOUNTS:");

        TaskDiscountsTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        TaskDiscountsTable.setModel(new TaskDiscountTableModel());
        jScrollPane3.setViewportView(TaskDiscountsTable);

        TaskTypeDropDown.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        String[] JobTypes = Processing.Controller.getTaskTypeStrings();
        TaskTypeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(JobTypes));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("AMOUNT:");

        PercentageText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30,30,30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(NameText)
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(TaskTypeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(PercentageText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(AddButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmButton2))
                .addComponent(ErrLabel))
                    .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                    .addComponent(ErrLabel)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskTypeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(PercentageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton)
                )

                    .addGap(18, 18, 18)
                .addComponent(ConfirmButton2)
                    .addGap(18,18,18)

                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Float amount = Float.parseFloat(PercentageText.getText());
                Integer index = TaskTypeDropDown.getSelectedIndex();

                if (amount > .5 & ErrLabel.getText().isBlank()) {
                    ErrLabel.setText("Current amount is " + ((Float)(amount*100f)).toString() + "% Are you sure?" );
                    return;
                }

                if ( ((TaskDiscountTableModel)TaskDiscountsTable.getModel()).hasElementOfTaskType(index) ) {
                    ErrLabel.setText("TaskType already discounted");
                    return;
                }

                ErrLabel.setText("");

                TaskPercentPair data = new TaskPercentPair(index+1, amount);
                System.out.println(index+1);
                discountArray.add(data);

                ((TaskDiscountTableModel)TaskDiscountsTable.getModel()).addElement(index, amount);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButton2MouseClicked
        if (NameText.getText().isBlank()) {
            ErrLabel.setText("Name must not be blank");
            return;
        }

        if (DescriptionText.getText().isBlank()) {
            ErrLabel.setText("Description must not be blank");
            return;
        }

        Discount d = DiscountController.createVariableDiscountPlan(NameText.getText(), DescriptionText.getText(), discountArray);
        ((DiscountTableModel)Parent.getDiscountTable().getModel()).addDiscount(d);

        this.dispose();
    }//GEN-LAST:event_ConfirmButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TaskDiscountsTable;
    private javax.swing.JButton ConfirmButton2;
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField DescriptionText;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField PercentageText;
    private javax.swing.JComboBox<String> TaskTypeDropDown;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel ErrLabel;
    // End of variables declaration//GEN-END:variables
}
